production:
  title      : Joruri
  uri        : http://192.168.0.2/
  http_proxy : <%= ENV['HTTP_PROXY'] %>
  https_proxy: <%= ENV['HTTPS_PROXY'] %>

test:
  title      : 
  uri        : 
  http_proxy :
  https_proxy:

development:
  title      : 
  uri        : 
  http_proxy :
  https_proxy:
